version: '3'
services:
  service:
    build:
      context: ./app
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/opt/app/static
      - media:/opt/app/media
    ports:
      - "80:80"
    depends_on:
      - service
    restart: always

  db:
    image: "postgres:13"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

volumes:
  static:
  media:
  postgres_volume:
